### PR TITLE
Featurebranch

### PR DESCRIPTION
**Pull request by karmaester**
Here are all the files the page was built on, including index, css files, and images.

### CODE REVIEW

**Review by kevcap — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUIRED♻️

 
### Hi team, you guys did a very good job so far! 💪
Amazing use of semantic HTML5, repo & code also very clean and professional. 👏👌
Nice choice of video (that's one of my favorite channels) 👽

#### I know you guys are working hard at this project, and you're almost done, there are just some required changes* that you guys have to implement in order to proceed:

[REQUIRED CHANGES]
- [ ] Your code is throwing some errors and warnings at the [HTML5 Validator](https://validator.w3.org/nu/#textarear), please fix them <sup>1</sup>
- [ ] Remove all the unnecessary repeated CSS code ([Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/))

[OPTIONAL CHANGES]
- [ ] Fix the description section to make your's more similar to the original one.
- [ ] Implement the comments section - It will make your clone looks more like to the original one.

Tip: Always use the HTML5 Validator in your projects

### Images:
* The validator is throwing some errors and warnings:
image
You can check those errors [here](https://validator.w3.org/nu/?doc=https%3A%2F%2Fgithub.com%2Fkarmaester%2FYoutube-Cloned%2Fblob%2Ffeaturebranch%2Findex.html)
<br><br>
* In your CSS files, there's a lot of repeated rules. e.g.: Instead of having 9x `width: 100%;`, create a single class: `.width-100 { 
width: 100% 
}`   and apply it in your HTML file.
image

<br><br>
* Description section (Optional)
<table>
<tbody>
<tr>
<td>Yours</td>
<td>Original</td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</tbody>
</table>

* Comments section (Optional)
<table>
<tbody>
<tr>
<td>Yours</td>
<td>Original</td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</tbody>
</table>



**Please make the required changes and resubmit for a new code review once you are ready**

 

As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

 

 

📫 Have any question? Better call Kevin:

 

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

**Review by lmaldonadoch — CHANGES_REQUESTED** [review]
# Changes Required 🥇 🏃‍♂️

## Great job, team!!! 🏆

You make this look so easy! You guys did an amazing job cloning the page, it looks almost identical to the original! Your CSS is well structured, although I would recommend the use of one file per page. Once you get to Rails or React, having so many CSS files becomes very impractical.

There is one mandatory requirement that you missed, and that needs to be completed before moving into the next section. Here it goes.

- [x] [REQUIRED] Your HTML is still not passing some validations with the HTML markup validator. Please make sure the tests are passing as described [here](https://github.com/microverseinc/linters-config/tree/Stickler/html_validator).
image

- [x] [OPTIONAL] The size of the images on the recommended videos is responsive, but the video is not; it was hard to find the resolution that you used for the development. You can try to fix it but is not required.




You guys did an amazing job, keep it going! :clap:

Please implement the required changes, and think about the optional ones.

It was a pleasure reviewing your code,

Happy coding! 💻

Slack: Luis Angel Maldoando
[LinkedIn](https://www.linkedin.com/in/lmaldonadoch/)

**Comment by len23** [comment]
Fixed All the HTML warnings and giving responsive units to the video

**Review by MuriloRoque — APPROVED** [review]
# Status: Approved :green_circle: 

## Hello @karmaester and @len23 :wave: 

## Congratulations, you have done an amazing job, your project is approved :clap: :clap: 

## Good luck with your next projects, you may merge :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
